include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_relative_imports

analyzer:
  exclude: [build/**, lib/generated/**]
